### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by adbrebs** [adbrebs/taxi#4]
- [x] RNN
- [x] tester différents embeddings
- [ ] essayer métrique
- [x] memory network
- [ ] essayer des modèles plus gros pour overfitter
- [ ] entraîner 1 modèle par taille de chemin
